### ISSUE TITLE
The game renders outside of the window

### ISSUE THREAD

**Issue by Moosichu** [pyland/pyland#141]
At the moment. (on the Raspberry Pi v2) the main game display renders outside of the window. (offset slightly upwards and leftwards.) T

**Comment by asb** [comment]
Possibly been a change to the handling of HDMI overscan. There was some fiddling getting that right (minecraft pi for instance has always been rendered outside of the main window on most screens).

**Comment by Moosichu** [comment]
ok, I have been looking at the code and managed to find a way to get it to work, but I'm not entirely sure if this is a correct way to do it.

Every time we run Pyland, the terminal displays: "Unable to query overscan using /boot/config.txt. Using defaults"
So I looked in game_window.cpp where that message seemed to be coming from.

from lines 55 -> 71 "#ifdef STATIC_OVERSCAN".... I played around with the values that where there. The values inside of the if statement "#define OVERSCAN_LEFT 24.." proved to make everything work when I made them the default values. Is this the correct why of fixing things?

**Comment by asb** [comment]
It fixes the immediate problem, but lets keep this bug open as a real fix should query the overscan settings via another mechanism. This should be possible via the VideoCore mailbox mechanism. Obviously this is low priority vs other things we'd like to tackle!

**Comment by ashleynewson** [comment]
Version 1 of the Raspberry Pi did indeed store overscan settings in /boot/config.txt. The reason this file was used to query the overscan is because there didn't appear to be any other obvious user-space method (even one as the root user) to get the overscan settings. As Version 2 of the Pi stores things significantly differently, this no longer works.

The STATIC_OVERSCAN was an original method which existed before overscan querying was implemented, based on the default overscan settings of the Pi at the time, and kept because I was afraid something like this would happen. The reason the whole mess exists is because the EGL framebuffer ignores overscan whilst the rest of the things on the Pi (such as VTs and X server) are bounded by it. The game_window tries to take this into account to align them.

If you notice that when de-focusing the window that alignment is correct, this is because the rendering is temporarily relayed through the SDL window - to prevent the Pyland rendering clobbering your view of other windows, as EGL framebuffers typically render infront of the X server.

It may be worth checking whether there has been any new way of querying overscan added in Version 2 which doesn't require directly looking inside boot files - but backwards compatibility may still require a test for /boot/config.txt.
