### ISSUE TITLE
Fix move(east) etc API

### ISSUE THREAD

**Issue by asb** [pyland/pyland#98]
Right now variables like east, north, west, south are automagically injected into the script. This is confusing for newbies and so we should have move("east") and/or move_east() as accepted APIs.

**Comment by sams25** [comment]
Also, because east, west etc are constants, there is a different kind of bug. move((20, 20)) will take move a sprite 20 places to the east and 20 places to the north if that position is not blockes irrespective of whether a path to that position exists or not. So we should indeed change the API to move_east()/move_west() etc

**Comment by heidi-ann** [comment]
Nice spot, i think this would be a worthwhile improvement. Maybe you can get some feedback on this issues at the open day

**Comment by sams25** [comment]
The api has now been changed for move. It is yet to be done for cut.

**Comment by sams25** [comment]
It's been done completely. Cut() now cuts the object in front
